services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server1
      - server2
    networks:
      - backend-network

  server1:
    image: web-app
    environment:
      - SERVER_ID=1
    ports:
      - "8001:80"
    networks:
      - backend-network

  server2:
    image: web-app
    environment:
      - SERVER_ID=2
    ports:
      - "8002:80"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

# services:
#   nginx:
#     image: nginx:alpine
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#     depends_on:
#       - server1
#       - server2
#     networks:
#       - backend-network

#   server1:
#     image: web-app
#     environment:
#       - SERVER_ID=1
#     ports:
#       - "8001:80"
#     networks:
#       - backend-network

#   server2:
#     image: web-app
#     environment:
#       - SERVER_ID=2
#     ports:
#       - "8002:80"
#     networks:
#       - backend-network

# networks:
#   backend-network:
#     driver: bridge